/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;

class AppTest {
     @Test
    public void testTask2_removesFirstCharacter() {
        SimpleFunctions sf = new SimpleFunctions();
        List<String> input = Arrays.asList("Apple", "Banana", "Cat");
        List<String> expected = Arrays.asList("pple", "anana", "at");
        assertEquals(expected, sf.Task2(input));
    }

    @Test
    public void testTask2_ignoresEmptyStrings() {
        SimpleFunctions sf = new SimpleFunctions();
        List<String> input = Arrays.asList("", "A", "", "Dog");
        List<String> expected = Arrays.asList("", "og");
        assertEquals(expected, sf.Task2(input));
    }

}


